# Generated by Django 4.0.3 on 2022-04-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurslar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='fan',
            name='oqituvchilar',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='yonalish',
        ),
        migrations.RemoveField(
            model_name='yonalish',
            name='boshlangan_sana',
        ),
        migrations.AddField(
            model_name='fan',
            name='code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fan',
            name='start_date',
            field=models.DateField(default='2007-03-12'),
        ),
        migrations.AddField(
            model_name='yonalish',
            name='fanlar',
            field=models.ManyToManyField(to='kurslar.fan'),
        ),
        migrations.DeleteModel(
            name='Oqituvchi',
        ),
        migrations.AddField(
            model_name='yonalish',
            name='ustozlar',
            field=models.ManyToManyField(to='kurslar.ustoz'),
        ),
    ]
